site_name: Rayforce-Py
repo_url: https://github.com/RayforceDB/rayforce-py
repo_name: GitHub

theme:
  name: material
  icon:
    repo: fontawesome/brands/github 
  favicon: assets/logo.png
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Outfit
    code: JetBrains Mono
  logo: assets/logo.png


extra:
    social:
      - icon: fontawesome/brands/github 
        link: https://github.com/RayforceDB/rayforce-py

copyright: Copyright &copy; 2025 RayforceDB

plugins:
  - offline
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - admonition
  - footnotes

extra_css:
  - https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&display=swap
  - https://adobe-fonts.github.io/source-code-pro/source-code-pro.css
  - css/custom.css
  - css/hero.css

nav:
  - Home: index.md
  - Get Started:
    - Overview: content/get-started/overview.md
    - Performance: content/get-started/performance.md
  - Documentation:
    - Overview: content/documentation/overview.md
    - Data Types:
      - Overview: content/documentation/data-types/overview.md
      - Integers: content/documentation/data-types/integers.md
      - Float: content/documentation/data-types/float.md
      - Unsigned Integer: content/documentation/data-types/unsigned-integer.md
      - Char: content/documentation/data-types/char.md
      - Symbol: content/documentation/data-types/symbol.md
      - Boolean: content/documentation/data-types/boolean.md
      - Temporal: content/documentation/data-types/temporal.md
      - GUID: content/documentation/data-types/guid.md
      - String: content/documentation/data-types/string.md
      - Vector: content/documentation/data-types/vector.md
      - List: content/documentation/data-types/list.md
      - Dict: content/documentation/data-types/dict.md
      - Table:
        - Overview: content/documentation/data-types/table/overview.md
        - Create: content/documentation/data-types/table/create.md
        - Access Values: content/documentation/data-types/table/access-values.md
        - Save and Fetch: content/documentation/data-types/table/save-and-fetch.md
        - Set Splayed: content/documentation/data-types/table/set-splayed.md
    - Query Guide:
      - Overview: content/documentation/query-guide/overview.md
      - Select: content/documentation/query-guide/select.md
      - Insert: content/documentation/query-guide/insert.md
      - Upsert: content/documentation/query-guide/upsert.md
      - Update: content/documentation/query-guide/update.md
      - Joins: content/documentation/query-guide/joins.md
      - Order By: content/documentation/query-guide/order-by.md
      - Group By: content/documentation/query-guide/group-by.md
    - Plugins:
      - Overview: content/documentation/plugins/overview.md
      - KDB: content/documentation/plugins/kdb.md
    - Development:
      - Overview: content/documentation/development/overview.md
  - License: content/license.md
