site_name: Rayforce-Py
repo_url: https://github.com/RayforceDB/rayforce-py
repo_name: GitHub

theme:
  name: material
  icon:
    repo: fontawesome/brands/github 
  favicon: assets/logo.png
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Outfit
    code: JetBrains Mono
  logo: assets/logo.png


extra:
    social:
      - icon: fontawesome/brands/github 
        link: https://github.com/RayforceDB/rayforce-py

copyright: Copyright &copy; 2025 RayforceDB

plugins:
  - offline
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - admonition
  - footnotes

extra_css:
  - https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&display=swap
  - https://adobe-fonts.github.io/source-code-pro/source-code-pro.css
  - css/custom.css
  - css/hero.css

nav:
  - Home: index.md
  - Get Started:
    - Overview: content/get-started/overview.md
    - Performance: content/get-started/performance.md
    - Contributing: content/get-started/contributing.md
  - Documentation:
    - Overview: content/documentation/overview.md
    - Data Types:
      - Overview: content/documentation/data-types/overview.md
      - Integers: content/documentation/data-types/integers.md
      - Float: content/documentation/data-types/float.md
      - Unsigned Integer: content/documentation/data-types/unsigned-integer.md
      - Char: content/documentation/data-types/char.md
      - Symbol: content/documentation/data-types/symbol.md
      - Boolean: content/documentation/data-types/boolean.md
      - Temporal: content/documentation/data-types/temporal.md
      - GUID: content/documentation/data-types/guid.md
      - String: content/documentation/data-types/string.md

    # REWORK:
    - Types Overview:
      - Container Types:
        - Vector: content/types/vector.md
        - List: content/types/list.md
        - String: content/types/string.md
        - Dict: content/types/dict.md
        - Table: content/types/table.md
    - Query Guide:
      - Overview: content/queries/index.md
      - Creating Tables: content/queries/tables.md
      - SELECT: content/queries/select.md
      - WHERE: content/queries/where.md
      - ORDER BY: content/queries/order-by.md
      - GROUP BY: content/queries/group-by.md
      - JOIN: content/queries/join.md
      - UPDATE: content/queries/update.md
      - INSERT: content/queries/insert.md
      - UPSERT: content/queries/upsert.md
      - Table Management: content/queries/management.md
    - Plugins:
      - KDB: content/plugins/kdb.md
    - Dev:
      - Lint and type: content/lint.md
      - Tests: content/tests.md
  - License: content/license.md
